
### Correct Sign On
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username": "user_1",
    "password": "password123"
}

### Incorrect Password
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username": "user_1",
    "password": "incorrect password"
}

### Incorrect Username
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username": "user_2",
    "password": "password123"
}

### Driver Login
POST http://localhost:3001/ap3/driver-login/
Content-Type: application/json

{
    "email": "forestschwrtz@gmail.com",
    "password": "password123"
}