
### Correct Sign On
POST http://localhost:3003/login/
Content-Type: application/json

{
    "username": "user_1",
    "password": "password123"
}

### Incorrect Password
POST http://localhost:3003/login/
Content-Type: application/json

{
    "username": "user_1",
    "password": "incorrect password"
}

### Incorrect Username
POST http://localhost:3003/login/
Content-Type: application/json

{
    "username": "user_2",
    "password": "password123"
}

### Driver Login
POST http://localhost:3003/login-driver/
Content-Type: application/json

{
    "email": "forestschwrtz@gmail.com",
    "password": "password123"
}

### Incorrect Driver Login
POST http://localhost:3003/login-driver/
Content-Type: application/json

{
    "email": "forestschwrtz@gmail.com",
    "password": "password12"
}


### Correct Sign On
POST http://routeoptimization-env.eba-chpd6puw.us-west-1.elasticbeanstalk.com/login/
Content-Type: application/json

{
    "username": "user_1",
    "password": "password123"
}