
### Correct Sign On
GET http://localhost:3003/users
Content-Type: application/json


### Incorrect User Schema
POST http://localhost:3003/users
Content-Type: application/json

{
    "username": "user_23",
    "password": "gotcha :p"
}


### Incorrect Password
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "user_1",
    "password": "incorrect password"
}

### Incorrect Username
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username": "user_2",
    "password": "password123"
}



### New Sign Up User
POST http://localhost:3003/api/users/signup/
Content-Type: application/json

{
    "first_name": "forest",
    "last_name": "schwartz",
    "email": "forestschwrtz@gmail.com",
    "password": "password123",
    "phone": "123-456-7890"
}


