AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simplified AWS Lambda function.

Resources:
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
          - X-Amz-User-Agent
        AllowOrigins:
          - '*' # Update this to your specific origin in production

  GetRoutesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.get_routes
      Runtime: python3.10
      CodeUri: .
      Events:
        GetApi:
          Type: HttpApi
          Properties:
            Path: /getRoutes
            Method: GET
            ApiId:
              Ref: MyHttpApi

  CreateRoutesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.create_routes
      Runtime: python3.10
      CodeUri: .
      Events:
        PostApi:
          Type: HttpApi
          Properties:
            Path: /createRoutes
            Method: POST
            ApiId:
              Ref: MyHttpApi

  AnalyzeRouteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.analyze_route
      Runtime: python3.10
      CodeUri: .
      Events:
        PostApi:
          Type: HttpApi
          Properties:
            Path: /analyzeRoute
            Method: POST
            ApiId:
              Ref: MyHttpApi