
### Get Request to Lambda
GET https://ldryzqul7l.execute-api.us-west-1.amazonaws.com/getRoutes
Content-Type: application/json


### Post Request to Lambda
POST https://ldryzqul7l.execute-api.us-west-1.amazonaws.com/createRoutes
Content-Type: application/json

{
    "username": "user_1",
    "password": "incorrect password"
}