export enum ActionType {
    ADD_LANDFILL = 'add_landfill',
    ADD_REGION = 'add_region',
    ADD_DEPOT = 'add_depot',
    ADD_DRIVER = 'add_driver',
    ADD_VEHICLE = 'add_vehicle',
    DELETE_LANDFILL = 'delete_landfill',
    DELETE_REGION = 'delete_region',
    DELETE_DEPOT = 'delete_depot',
    DELETE_DRIVER = 'delete_driver',
    DELETE_VEHICLE = 'delete_vehicle',
    UPDATE_LANDFILL = 'update_landfill',
    UPDATE_DRIVER = 'update_driver',
    UPDATE_DEPOT = 'update_depot',
    UPDATE_VEHICLE = 'update_vehicle',
    INIT_LANDFILLS = 'init_landfills',
    INIT_REGIONS = 'init_regions',
    INIT_DRIVERS = 'init_drivers',
    INIT_DEPOTS = 'init_depots',
    INIT_VEHICLES = 'init_vehicles',
    SET_USER_TOKEN = 'set_user_token',
    SET_REGION = 'set_region',
}