export const ERROR_CODES = {
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  TOKEN_NOT_FOUND: "TOKEN NOT FOUND",
  LOGIN_ERROR: "LOGIN_ERROR",
  USER_CREATION_ERROR: "USER_CREATION_ERROR",
};
